---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: aws-example-octodex
  replicas: 1 
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 191896455525.dkr.ecr.ap-southeast-2.amazonaws.com/example-eks:43e4c9d7c4aa2af31232def4dbb14b176d7cb226
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: aws-example-octodex
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: aws-example-octodex
